server {
    listen       80;
    server_name  localhost;

    charset utf-8;

    access_log  /var/log/nginx/access.log  ltsv;
    error_log   /var/log/nginx/error.log   warn;

    location / {
        root   /var/apps/current/public;
        index  index.html;
        add_header Cache-Control "max-age=86400, no-cache";
    }

    location ~ \.php$ {
        root           /var/apps/current/public;
        fastcgi_pass   unix:/var/run/php-fpm/php-fpm.sock;
        fastcgi_index  index.php;
        fastcgi_param  SCRIPT_FILENAME $document_root/$fastcgi_script_name;
        include        fastcgi_params;
        add_header Cache-Control "no-cache, no-store, must-revalidate";
    }

    location ~ /\.ht {
        deny  all;
    }
}

