- block:
  - name: include common variables
    include_vars: "main.yml"
  
  - name: include environment specific variables
    include_vars: "{{ stage }}.yml"
  tags:
    - always

- block:
  - name: set locale to en_US.utf8
    copy:
      src: "system/locale.conf"
      dest: "/etc/locale.conf"
      owner: "root"
      group: "root"
      mode: 0644

  - name: disable ipv6
    copy:
      src: "system/disable_ipv6.conf"
      dest: "/etc/sysctl.d/disable_ipv6.conf"
      owner: "root"
      group: "root"
      mode: 0644

  - name: set timezone to Asia/Tokyo
    timezone:
      name: "Asia/Tokyo"

  - name: disable selinux
    selinux:
      state: "disabled"
    when: ansible_distribution in ["CentOS"]

  - name: disable firewalld
    systemd:
      name: "firewalld"
      enabled: "no"

  - name: setup shell prompt
    lineinfile:
      dest: "/etc/profile"
      state: "present"
      line: 'PS1="({{ stage }})[\u@\h \W]\$ "'
  tags: ["never", "setup"]

- block:
  - name: install yum base packages
    yum:
      name: "{{ yum_base_packages }}"
      state: "latest"

  - name: install pip base packages
    pip:
      name: "{{ pip_base_packages }}"
      state: "latest"
  tags: ["never", "setup", "update"]

